# Generated by Django 4.2.5 on 2023-10-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_subject', models.CharField(max_length=200)),
                ('contact_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_area', models.CharField(max_length=100)),
                ('hotel_beds', models.PositiveSmallIntegerField()),
                ('hotel_accommodates', models.PositiveSmallIntegerField()),
                ('hotel_star_rating', models.PositiveSmallIntegerField(default=0)),
                ('hotel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_image', models.ImageField(upload_to='hotel_images/')),
                ('images', models.ManyToManyField(to='resortapp.hotelimage')),
            ],
        ),
    ]
