# Generated by Django 4.2.5 on 2023-11-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_image',
            new_name='main_hotel_image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_accommodates',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_amenities',
            field=models.ManyToManyField(to='resortapp.amenity'),
        ),
    ]
