# Generated by Django 4.2.5 on 2023-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0002_amenity_rename_hotel_image_hotel_main_hotel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contact Number'),
        ),
    ]
