# Generated by Django 4.2.5 on 2023-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0003_contactmessage_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
