# Generated by Django 4.2.5 on 2023-11-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0005_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_star_rating',
        ),
    ]
