# Generated by Django 4.2.5 on 2023-11-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0006_remove_hotel_hotel_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_star_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
